trigger:
- main

pool:
  name: 'SelfHosted'   # use your pool

variables:
  pythonVersion: '3.10'
  webAppName: 'flaskml-jana-151905'
  resourceGroup: 'udacity-rg-centralus'
  artifactName: 'drop'
  packagePath: '$(Build.ArtifactStagingDirectory)/drop.zip'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    make lint
    make test
  displayName: 'Install, Lint, Test'

- task: ArchiveFiles@2
  displayName: 'Create deployment package'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/drop.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: '$(artifactName)'

- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: 'azure-spn'
    appType: 'webAppLinux'
    appName: '$(webAppName)'
    package: '$(packagePath)'

